export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  SET_CATEGORY: "SET_CATEGORY",
  GET_CATEGORY_ID: "GET_CATEGORY_ID",
  SIGN_OUT_TOKEN: "SIGN_OUT_TOKEN",
  LOGIN_TOKEN: "LOGIN_TOKEN",
};
